# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Bergrübe
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of TSDProxy systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ tsdproxy_identifier }}.service"
  register: tsdproxy_service_stat

- name: Uninstall TSDProxy systemd services and files
  when: tsdproxy_service_stat.stat.exists | bool
  block:
    - name: Ensure TSDProxy service is stopped
      ansible.builtin.service:
        name: "{{ tsdproxy_identifier }}"
        state: stopped
        daemon_reload: true
    - name: Ensure TSDProxy service doesn't exist
      ansible.builtin.file:
        dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ tsdproxy_identifier }}.service"
        state: absent

    - name: Ensure TSDProxy base path is files deleted (make sure to delete node data)
      ansible.builtin.file:
        path: "{{ tsdproxy_base_path }}"
        state: absent
